packages:
  - turbo
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  dev:
    "@tailwindcss/vite": ^4.1.13
    "@testing-library/jest-dom": ^6.8.0
    "@types/chrome": ^0.1.6
    "@vitejs/plugin-react": ^5.0.2
    '@babel/core': ^7.28.3
    '@pixpilot/dev-config': ^3.1.2
    '@testing-library/react': ^14.0.0
    '@types/node': ^22.17.2
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.7
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    "typescript-eslint": ^8.40.0
    autoprefixer: ^10.4.21
    eslint: ^9.34.0
    postcss: ^8.5.6
    prettier: ^3.6.2
    tailwindcss: 4.1.12
    typescript: ^5.9.2
    vite: ^7.1.4
    vitest: ^3.2.4

  prod:
    react: 19.0.0
    react-dom: 19.0.0
    zod: 4.0.17
